### **Vectors and Matrices in Quantum Mechanics**

In quantum mechanics, the state of a system is represented by a **vector** (called a state vector or ket).  
For example, a single qubit state is represented as:

$$
|\psi\rangle = \alpha |0\rangle + \beta |1\rangle =
\begin{bmatrix}
\alpha \\
\beta
\end{bmatrix}
$$

where $\alpha$ and $\beta$ are complex numbers satisfying the normalization condition:

$$
|\alpha|^2 + |\beta|^2 = 1
$$

Here, $|0\rangle = \begin{bmatrix}1 \\ 0\end{bmatrix}$ and $|1\rangle = \begin{bmatrix}0 \\ 1\end{bmatrix}$.

Matrices appear naturally in quantum mechanics because **operators** (such as measurements and quantum gates) are represented by matrices that act on state vectors.  
For example, the **Pauli-X gate** (a quantum version of the NOT operation) is:

$$
X = 
\begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix}
$$

When applied to a state vector, it flips the amplitudes of $|0\rangle$ and $|1\rangle$:

$$
X|0\rangle = |1\rangle, \quad X|1\rangle = |0\rangle
$$

Thus, vectors represent quantum states, and matrices represent transformations (unitary operators or observables). Together, they form the mathematical foundation of quantum mechanics.


In [1]:
import numpy as np

# Define basis vectors |0> and |1>
zero = np.array([[1], [0]])
one = np.array([[0], [1]])

# Define Pauli-X matrix
X = np.array([[0, 1],
              [1, 0]])

# Apply X gate to |0> and |1>
X_zero = X @ zero
X_one = X @ one

print("Pauli-X acting on |0> gives:\n", X_zero)
print("\nPauli-X acting on |1> gives:\n", X_one)

# Example of a quantum state |ψ> = α|0> + β|1>
alpha, beta = 1/np.sqrt(2), 1/np.sqrt(2)  # normalized state
psi = alpha * zero + beta * one
print("\nQuantum state |ψ> = (1/sqrt(2))|0> + (1/sqrt(2))|1>:\n", psi)

# Apply Pauli-X to |ψ>
psi_after_X = X @ psi
print("\nState after applying X to |ψ>:\n", psi_after_X)

Pauli-X acting on |0> gives:
 [[0]
 [1]]

Pauli-X acting on |1> gives:
 [[1]
 [0]]

Quantum state |ψ> = (1/sqrt(2))|0> + (1/sqrt(2))|1>:
 [[0.70710678]
 [0.70710678]]

State after applying X to |ψ>:
 [[0.70710678]
 [0.70710678]]


### **Inner Product and Outer Product in Quantum Mechanics**

In quantum mechanics, the **inner product** and **outer product** play fundamental roles:

#### **Inner Product**
The inner product between two state vectors $|\psi\rangle$ and $|\phi\rangle$ is written as:

$$
\langle \phi | \psi \rangle
$$

- It is a **complex number**.
- Physically, it represents the **overlap** or **similarity** between two quantum states.
- For normalized states, $|\langle \phi | \psi \rangle|^2$ gives the **probability** of measuring state $|\psi\rangle$ in the basis of $|\phi\rangle$.

Example:
$$
|0\rangle = \begin{bmatrix}1 \\ 0\end{bmatrix}, \quad
|1\rangle = \begin{bmatrix}0 \\ 1\end{bmatrix}
$$
$$
\langle 0 | 1 \rangle = 0, \quad \langle 0 | 0 \rangle = 1
$$

#### **Outer Product**
The outer product of two states is written as:

$$
|\psi\rangle \langle \phi |
$$

- It produces a **matrix (operator)**.
- Outer products are useful for constructing **projection operators** and **density matrices**.
- For example:
$$
|0\rangle \langle 0| =
\begin{bmatrix}
1 & 0 \\
0 & 0
\end{bmatrix}
$$

This is a projector onto the $|0\rangle$ state.

**Summary:**
- Inner product → complex number (overlap/probability amplitude).  
- Outer product → matrix (operator/projector).


In [2]:
import numpy as np

# Define basis vectors
zero = np.array([[1], [0]])
one = np.array([[0], [1]])

# Inner products
inner_00 = zero.T.conj() @ zero   # <0|0>
inner_01 = zero.T.conj() @ one    # <0|1>

print("Inner product <0|0> =", inner_00)
print("Inner product <0|1> =", inner_01)

# Outer products
outer_00 = zero @ zero.T.conj()   # |0><0|
outer_01 = zero @ one.T.conj()    # |0><1|

print("\nOuter product |0><0| =\n", outer_00)
print("\nOuter product |0><1| =\n", outer_01)

# General quantum state
alpha, beta = 1/np.sqrt(2), 1/np.sqrt(2)
psi = alpha*zero + beta*one

# Inner product of |ψ> with |0>
overlap = zero.T.conj() @ psi
print("\nInner product <0|ψ> =", overlap, " -> Probability =", np.abs(overlap[0,0])**2)

# Outer product |ψ><ψ| (density matrix for pure state)
rho = psi @ psi.T.conj()
print("\nOuter product |ψ><ψ| (Density matrix) =\n", rho)

Inner product <0|0> = [[1]]
Inner product <0|1> = [[0]]

Outer product |0><0| =
 [[1 0]
 [0 0]]

Outer product |0><1| =
 [[0 1]
 [0 0]]

Inner product <0|ψ> = [[0.70710678]]  -> Probability = 0.4999999999999999

Outer product |ψ><ψ| (Density matrix) =
 [[0.5 0.5]
 [0.5 0.5]]


### **Unitary and Hermitian Matrices in Quantum Mechanics**

#### **Unitary Matrices**
A matrix $U$ is **unitary** if:

$$
U^\dagger U = U U^\dagger = I
$$

where $U^\dagger$ is the **conjugate transpose** of $U$, and $I$ is the identity matrix.

- Unitary matrices preserve the length (norm) of vectors.
- In quantum mechanics, **time evolution** and **quantum gates** are always represented by unitary operators, because probabilities must remain normalized.
- Example: The Pauli-X gate  

$$
X = \begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix}
$$  

satisfies $X^\dagger X = I$, so it is unitary.

#### **Hermitian Matrices**
A matrix $H$ is **Hermitian** if:

$$
H^\dagger = H
$$

- Hermitian matrices have **real eigenvalues**.
- In quantum mechanics, **observables** (measurable quantities like energy, position, spin) are represented by Hermitian operators.
- Example: The Pauli-Z operator  

$$
Z = \begin{bmatrix}
1 & 0 \\
0 & -1
\end{bmatrix}
$$  

is Hermitian, and its eigenvalues $\{+1, -1\}$ correspond to possible measurement outcomes.

**Key Idea:**
- **Unitary operators** → evolution and quantum gates (preserve probability).  
- **Hermitian operators** → observables (measurement outcomes are real).


In [3]:
import numpy as np

# Define Pauli matrices
X = np.array([[0, 1],
              [1, 0]])

Z = np.array([[1, 0],
              [0, -1]])

# Check Unitarity: U†U = I
X_unitary_check = X.conj().T @ X
print("X†X =\n", X_unitary_check)

# Check Hermitian: H† = H
Z_hermitian_check = np.allclose(Z.conj().T, Z)
print("\nIs Z Hermitian? ->", Z_hermitian_check)

# Eigenvalues of Hermitian matrix (should be real)
eigvals_Z, eigvecs_Z = np.linalg.eig(Z)
print("\nEigenvalues of Z =", eigvals_Z)

# Example of time evolution operator (unitary)
theta = np.pi/4
U = np.array([[np.cos(theta), -1j*np.sin(theta)],
              [-1j*np.sin(theta), np.cos(theta)]])
print("\nU†U =\n", U.conj().T @ U)
print("Is U unitary? ->", np.allclose(U.conj().T @ U, np.eye(2)))


X†X =
 [[1 0]
 [0 1]]

Is Z Hermitian? -> True

Eigenvalues of Z = [ 1. -1.]

U†U =
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
Is U unitary? -> True


### **Diagonalization and Singular Values in Quantum Mechanics**

#### **Diagonalization**
A square matrix $A$ can be **diagonalized** if it can be written as:

$$
A = P D P^{-1}
$$

where:
- $D$ is a diagonal matrix containing the eigenvalues of $A$.
- $P$ contains the eigenvectors as columns.

In quantum mechanics:
- Hermitian operators (observables) are always diagonalizable.
- The diagonal form represents the operator in its **eigenbasis**.
- Example: The Pauli-Z operator  

$$
Z = \begin{bmatrix}
1 & 0 \\
0 & -1
\end{bmatrix}
$$  

is already diagonal. Its eigenvalues $\{+1, -1\}$ correspond to possible measurement results.

#### **Singular Value Decomposition (SVD)**
Any matrix $M$ (even non-square) can be written as:

$$
M = U \Sigma V^\dagger
$$

where:
- $U$ and $V$ are unitary matrices,  
- $\Sigma$ is a diagonal matrix with **non-negative real numbers** called **singular values**.

In quantum mechanics:
- SVD is useful in **quantum information** (entanglement, Schmidt decomposition).  
- The singular values represent the "strength" of each component in a quantum state or operator.

**Key Idea:**
- **Diagonalization** → applies to Hermitian matrices (observables).  
- **SVD** → applies to any matrix, useful for analyzing quantum sta


In [4]:
import numpy as np

# Example Hermitian matrix (Hamiltonian-like)
H = np.array([[2, 1],
              [1, 2]])

# Diagonalization
eigvals, eigvecs = np.linalg.eig(H)
D = np.diag(eigvals)
P = eigvecs
reconstructed_H = P @ D @ np.linalg.inv(P)

print("Original H =\n", H)
print("\nEigenvalues =", eigvals)
print("Eigenvectors (columns of P) =\n", P)
print("\nDiagonal form D =\n", D)
print("\nReconstructed H from diagonalization =\n", reconstructed_H)

# Example non-square matrix
M = np.array([[3, 1, 1],
              [-1, 3, 1]])

# Singular Value Decomposition
U, Sigma, Vh = np.linalg.svd(M)

print("\nU =\n", U)
print("\nSingular values =", Sigma)
print("\nV† =\n", Vh)

# Reconstruct M
Sigma_full = np.zeros_like(M, dtype=float)
np.fill_diagonal(Sigma_full, Sigma)
M_reconstructed = U @ Sigma_full @ Vh
print("\nReconstructed M =\n", M_reconstructed)


Original H =
 [[2 1]
 [1 2]]

Eigenvalues = [3. 1.]
Eigenvectors (columns of P) =
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Diagonal form D =
 [[3. 0.]
 [0. 1.]]

Reconstructed H from diagonalization =
 [[2. 1.]
 [1. 2.]]

U =
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular values = [3.46410162 3.16227766]

V† =
 [[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.26260748e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]

Reconstructed M =
 [[ 3.  1.  1.]
 [-1.  3.  1.]]


### **Tensor Products in Quantum Mechanics**

In quantum mechanics, when we have **multiple systems**, their joint state is described using the **tensor product** (also called the Kronecker product).

For two states $|\psi\rangle$ and $|\phi\rangle$:

$$
|\Psi\rangle = |\psi\rangle \otimes |\phi\rangle
$$

#### **Example**:
If  

$$
|\psi\rangle = \begin{bmatrix}1 \\ 0\end{bmatrix} = |0\rangle, \quad
|\phi\rangle = \begin{bmatrix}0 \\ 1\end{bmatrix} = |1\rangle
$$  

then:  

$$
|\Psi\rangle = |0\rangle \otimes |1\rangle =
\begin{bmatrix}
0 \\ 1 \\ 0 \\ 0
\end{bmatrix}
$$

This corresponds to the **two-qubit state** $|01\rangle$.

#### **Tensor Products of Operators**
Just like states, operators combine via tensor products:

$$
A \otimes B
$$

acts on the joint system, where $A$ acts on the first subsystem and $B$ on the second.

Example:
- Identity on the first qubit ($I$) and Pauli-X on the second ($X$):  

$$
I \otimes X =
\begin{bmatrix}
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0
\end{bmatrix}
$$

**Key Idea:**
- Tensor product of vectors → joint states (multi-qubit systems).  
- Tensor product of matrices → joint operators (multi-qubit gates).


In [ ]:
import numpy as np

# Define basis states
zero = np.array([[1], [0]])
one = np.array([[0], [1]])

# Tensor product of states |0> ⊗ |1> = |01>
psi = np.kron(zero, one)
print("Tensor product |0>⊗|1> = |01>:\n", psi)

# Another example: superposition state (|0>+|1>)/√2 ⊗ |0>
superposition = (zero + one) / np.sqrt(2)
psi2 = np.kron(superposition, zero)
print("\n(|0>+|1>)/√2 ⊗ |0>:\n", psi2)

# Define Pauli-X and Identity
X = np.array([[0, 1],
              [1, 0]])
I = np.eye(2)

# Tensor product of operators I⊗X
op = np.kron(I, X)
print("\nOperator I⊗X =\n", op)

# Apply (I⊗X) on |01> state
result = op @ psi
print("\n(I⊗X)|01> =\n", result)


### **Trace of a Matrix in Quantum Mechanics**

The **trace** of a square matrix $A$ is defined as the sum of its diagonal elements:

$$
\text{Tr}(A) = \sum_i A_{ii}
$$

#### **Properties**:
1. **Linearity:**  
$$
\text{Tr}(A + B) = \text{Tr}(A) + \text{Tr}(B), \quad
\text{Tr}(cA) = c \, \text{Tr}(A)
$$

2. **Cyclic Property:**  
$$
\text{Tr}(AB) = \text{Tr}(BA)
$$  
(This is very useful in quantum mechanics.)

3. **Unitary Invariance:**  
If $U$ is unitary,  
$$
\text{Tr}(U^\dagger A U) = \text{Tr}(A)
$$

---

### **Quantum Mechanics Context**
- The trace is used to compute **expectation values**:  

$$
\langle O \rangle = \text{Tr}(\rho O)
$$  

where $\rho$ is the **density matrix** of the state and $O$ an observable.

- The trace of a **density matrix** is always 1:  

$$
\text{Tr}(\rho) = 1
$$

Example:  
For pure state $|\psi\rangle = \tfrac{1}{\sqrt{2}}(|0\rangle+|1\rangle)$,  
its density matrix is:  

$$
\rho = |\psi\rangle\langle \psi| =
\frac{1}{2} 
\begin{bmatrix}
1 & 1 \\
1 & 1
\end{bmatrix}
$$  

and $\text{Tr}(\rho) = 1$.


In [5]:
import numpy as np

# Define a matrix
A = np.array([[2, 1],
              [0, 3]])

# Trace directly
trace_A = np.trace(A)
print("Trace of A =", trace_A)

# Verify cyclic property: Tr(AB) = Tr(BA)
B = np.array([[1, 2],
              [3, 4]])
lhs = np.trace(A @ B)
rhs = np.trace(B @ A)
print("\nTr(AB) =", lhs, ", Tr(BA) =", rhs)

# Example in quantum mechanics: density matrix
zero = np.array([[1], [0]])
one = np.array([[0], [1]])
psi = (zero + one) / np.sqrt(2)   # (|0>+|1>)/√2

rho = psi @ psi.T.conj()  # density matrix
print("\nDensity matrix ρ =\n", rho)

print("\nTrace of ρ =", np.trace(rho))  # should be 1

# Expectation value of Pauli-Z: <Z> = Tr(ρZ)
Z = np.array([[1, 0],
              [0, -1]])
expectation_Z = np.trace(rho @ Z)
print("\nExpectation value <Z> =", expectation_Z.real)


Trace of A = 5

Tr(AB) = 17 , Tr(BA) = 17

Density matrix ρ =
 [[0.5 0.5]
 [0.5 0.5]]

Trace of ρ = 0.9999999999999998

Expectation value <Z> = 0.0


In [6]:
import numpy as np

# Define Pauli matrices
X = np.array([[0, 1],
              [1, 0]], dtype=complex)
Y = np.array([[0, -1j],
              [1j, 0]], dtype=complex)
Z = np.array([[1, 0],
              [0, -1]], dtype=complex)
I = np.eye(2)

# Check Hermitian and Unitary
print("X is Hermitian?", np.allclose(X.conj().T, X))
print("X is Unitary?", np.allclose(X.conj().T @ X, I))

# Squares of Pauli matrices
print("\nX^2 =\n", X @ X)
print("Y^2 =\n", Y @ Y)
print("Z^2 =\n", Z @ Z)

# Commutation [X, Y] = 2iZ
comm_XY = X @ Y - Y @ X
print("\n[X, Y] =\n", comm_XY)

# Anti-commutation {X, Y} = XY + YX
anticomm_XY = X @ Y + Y @ X
print("\n{X, Y} =\n", anticomm_XY)

# Example: apply Pauli-X to |0>
zero = np.array([[1], [0]])
result = X @ zero
print("\nX|0> =\n", result)

# Example: spin observable along Z
psi = (zero + np.array([[0],[1]])) / np.sqrt(2)  # (|0>+|1>)/√2
expect_Z = np.vdot(psi, Z @ psi)
print("\nExpectation value <ψ|Z|ψ> =", expect_Z.real)


X is Hermitian? True
X is Unitary? True

X^2 =
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
Y^2 =
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
Z^2 =
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]

[X, Y] =
 [[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]

{X, Y} =
 [[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]

X|0> =
 [[0.+0.j]
 [1.+0.j]]

Expectation value <ψ|Z|ψ> = 0.0
